// One-time migration of the local SQLite database into Supabase.
//
//   node --env-file-if-exists=.env migrate.mjs --email you@example.com [--dry-run] [--reset]
//
// Two things make this simpler than it looks:
//
//   * Identity columns are GENERATED BY DEFAULT, so every SQLite primary key is inserted
//     verbatim and no foreign key needs remapping. Sequences are reset afterwards.
//   * Drizzle stored timestamps as epoch SECONDS, not milliseconds. Treating them as ms
//     yields 1970 dates that pass every type check, so the conversion is centralised here
//     and asserted by verify.mjs.

import { createClient } from "@supabase/supabase-js";
import Database from "better-sqlite3";
import { fileURLToPath } from "node:url";
import path from "node:path";

const argv = process.argv.slice(2);
const flag = (name) => argv.includes(`--${name}`);
const value = (name) => {
  const i = argv.indexOf(`--${name}`);
  return i >= 0 ? argv[i + 1] : undefined;
};

const EMAIL = value("email");
const DRY_RUN = flag("dry-run");
const RESET = flag("reset");

const here = path.dirname(fileURLToPath(import.meta.url));
const DB_PATH = value("db") ?? path.join(here, "fixtures/sqlite.db");

const URL = process.env.SUPABASE_URL;
const SECRET = process.env.SUPABASE_SECRET_KEY;

if (!EMAIL) {
  console.error("Usage: node migrate.mjs --email <account email> [--dry-run] [--reset]");
  process.exit(1);
}
if (!URL || !SECRET) {
  console.error("SUPABASE_URL and SUPABASE_SECRET_KEY must be set.");
  process.exit(1);
}

const admin = createClient(URL, SECRET, { auth: { persistSession: false } });
const sqlite = new Database(DB_PATH, { readonly: true });

/** Epoch seconds to ISO. The single most dangerous conversion in this script. */
const ts = (v) => (v == null ? null : new Date(v * 1000).toISOString());
/** Epoch seconds to a calendar day, for the body_stats.date column. */
const day = (v) => (v == null ? null : new Date(v * 1000).toISOString().slice(0, 10));
const bool = (v) => Boolean(v);
const json = (v) => {
  if (v == null) return null;
  if (typeof v === "object") return v;
  try {
    return JSON.parse(v);
  } catch {
    return null;
  }
};

async function findUser(email) {
  // listUsers is paginated; walk until the address turns up.
  for (let page = 1; page <= 20; page++) {
    const { data, error } = await admin.auth.admin.listUsers({ page, perPage: 200 });
    if (error) throw new Error(`listUsers: ${error.message}`);
    const hit = data.users.find(
      (u) => u.email?.toLowerCase() === email.toLowerCase(),
    );
    if (hit) return hit;
    if (data.users.length < 200) break;
  }
  return null;
}

async function insert(table, rows) {
  if (rows.length === 0) {
    console.log(`  ${table}: 0 rows, skipped`);
    return;
  }
  if (DRY_RUN) {
    console.log(`  ${table}: ${rows.length} rows (dry run)`);
    console.log(`    first: ${JSON.stringify(rows[0])}`);
    return;
  }
  for (let i = 0; i < rows.length; i += 500) {
    const chunk = rows.slice(i, i + 500);
    const { error } = await admin.from(table).insert(chunk);
    if (error) {
      throw new Error(`${table} insert failed: ${error.message} (${error.code ?? "?"})`);
    }
  }
  console.log(`  ${table}: ${rows.length} rows inserted`);
}

const main = async () => {
  const user = await findUser(EMAIL);
  if (!user) {
    console.error(
      `No account found for ${EMAIL}.\n` +
        "Sign up and confirm the address first, then re-run. This script deliberately does " +
        "not create the account, so the real signup flow and its trigger run once.",
    );
    process.exit(1);
  }
  const uid = user.id;
  console.log(`Target account: ${EMAIL} (${uid})`);
  console.log(`Source database: ${DB_PATH}${DRY_RUN ? "  [DRY RUN]" : ""}\n`);

  if (RESET && !DRY_RUN) {
    console.log("Resetting existing rows for this user...");
    // Children cascade from workouts and routines; delete the roots plus the independents.
    for (const table of [
      "body_stats",
      "weekly_split_days",
      "workout_sets",
      "workouts",
      "routine_exercises",
      "routines",
    ]) {
      await admin.from(table).delete().eq("user_id", uid);
    }
    await admin.from("exercises").delete().eq("user_id", uid);
    await admin.from("exercises").delete().is("user_id", null);
    console.log("  done\n");
  }

  const q = (sql) => sqlite.prepare(sql).all();

  // 1. Exercises. Seeded catalog rows become global (user_id null); user-made ones stay owned.
  const exercises = q("select * from exercises").map((r) => ({
    id: r.id,
    user_id: r.is_custom ? uid : null,
    name: r.name,
    primary_muscle_group: r.primary_muscle_group,
    secondary_muscle_groups: json(r.secondary_muscle_groups) ?? [],
    equipment: r.equipment,
    notes: r.notes,
    video_url: r.video_url,
    created_at: ts(r.created_at),
  }));

  const routines = q("select * from routines").map((r) => ({
    id: r.id,
    user_id: uid,
    name: r.name,
    description: r.description,
    created_at: ts(r.created_at),
    updated_at: ts(r.updated_at),
  }));

  const routineExercises = q("select * from routine_exercises").map((r) => ({
    id: r.id,
    user_id: uid,
    routine_id: r.routine_id,
    exercise_id: r.exercise_id,
    sort_order: r.order,
    target_sets: r.target_sets,
    target_reps_min: r.target_reps_min,
    target_reps_max: r.target_reps_max,
    target_rpe: r.target_rpe,
    rest_seconds: r.rest_seconds,
    group_id: r.group_id,
    group_type: r.group_type,
  }));

  const workouts = q("select * from workouts").map((r) => ({
    id: r.id,
    user_id: uid,
    date: ts(r.date),
    routine_id: r.routine_id,
    notes: r.notes,
    started_at: ts(r.started_at),
    finished_at: ts(r.finished_at),
    duration_seconds: r.duration_seconds,
  }));

  const workoutSets = q("select * from workout_sets").map((r) => ({
    id: r.id,
    user_id: uid,
    workout_id: r.workout_id,
    exercise_id: r.exercise_id,
    set_number: r.set_number,
    weight: r.weight,
    reps: r.reps,
    rpe: r.rpe,
    is_warmup: bool(r.is_warmup),
    is_pr: bool(r.is_pr),
    group_id: r.group_id,
    completed_at: ts(r.completed_at),
  }));

  const bodyStats = q("select * from body_stats").map((r) => ({
    id: r.id,
    user_id: uid,
    date: day(r.date),
    weight_kg: r.weight_kg,
    measurements: json(r.measurements),
    photo_url: r.photo_url,
    notes: r.notes,
  }));

  const splitDays = q("select * from weekly_split_days").map((r) => ({
    id: r.id,
    user_id: uid,
    day_of_week: r.day_of_week,
    label: r.label,
    routine_id: r.routine_id,
  }));

  const [settingsRow] = q("select * from settings");

  console.log("Inserting (order matters for foreign keys):");
  await insert("exercises", exercises);
  await insert("routines", routines);
  await insert("routine_exercises", routineExercises);
  await insert("workouts", workouts);
  await insert("workout_sets", workoutSets);
  await insert("body_stats", bodyStats);
  await insert("weekly_split_days", splitDays);

  // The settings row is keyed by user, not by its old id = 1. The signup trigger already
  // created a default row, so this is an update rather than an insert.
  if (settingsRow && !DRY_RUN) {
    const { error } = await admin
      .from("user_settings")
      .update({
        weight_unit: settingsRow.weight_unit,
        default_rest_seconds: settingsRow.default_rest_seconds,
      })
      .eq("user_id", uid);
    if (error) throw new Error(`user_settings: ${error.message}`);
    console.log("  user_settings: updated");
  }

  if (!DRY_RUN) {
    // Explicit ids leave the sequences at 1, so the next app insert would collide.
    const { error } = await admin.rpc("reset_identity_sequences");
    if (error) throw new Error(`reset_identity_sequences: ${error.message}`);
    console.log("  sequences: realigned to max(id)");
    console.log("\nDone. Run verify.mjs to confirm the data survived the trip.");
  }
};

main()
  .catch((err) => {
    console.error(`\nMigration failed: ${err.message}`);
    process.exit(1);
  })
  .finally(() => sqlite.close());
