-- Realigns every identity sequence with the largest id currently in its table.
--
-- The SQLite migration inserts explicit primary keys (the columns are GENERATED BY DEFAULT
-- precisely so it can), which leaves each sequence still sitting at 1. Without this the next
-- application insert collides with a migrated row and fails on the primary key.
--
-- Restricted to service_role: it is a migration tool, not something a logged-in user should
-- ever be able to call.

create or replace function public.reset_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
  seq text;
begin
  foreach t in array array[
    'exercises','routines','routine_exercises','workouts',
    'workout_sets','body_stats','weekly_split_days'
  ]
  loop
    seq := pg_get_serial_sequence('public.' || t, 'id');
    if seq is not null then
      execute format(
        'select setval(%L, coalesce((select max(id) from public.%I), 1), true)',
        seq, t
      );
    end if;
  end loop;
end;
$$;

revoke all on function public.reset_identity_sequences() from public, anon, authenticated;
grant execute on function public.reset_identity_sequences() to service_role;
