-- GymTracker initial schema.
--
-- Design notes that matter:
--   * Identity columns are GENERATED BY DEFAULT, not ALWAYS, so the SQLite migration can
--     insert explicit ids and preserve every existing primary key and foreign key verbatim.
--   * Vocabularies are text + CHECK rather than native enum types, so adding a muscle group
--     later is a one-line migration instead of an ALTER TYPE. Keep these lists in sync with
--     packages/shared/src/enums.ts.
--   * user_id is denormalised onto the child tables (routine_exercises, workout_sets) so their
--     RLS policies can be an indexed equality test instead of a per-row EXISTS against the
--     parent. The composite foreign keys below make it structurally impossible for a child to
--     point at another user's parent, so the denormalisation cannot drift.

create extension if not exists pg_trgm;

-- ---------- Exercises ----------
-- user_id NULL means a global catalog row visible to everyone; non-null means that user's
-- custom exercise. is_custom is dropped and derived as (user_id is not null) by the API.

create table exercises (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  primary_muscle_group text not null check (primary_muscle_group in (
    'chest','back','shoulders','biceps','triceps','forearms',
    'quads','hamstrings','glutes','calves','abs','full_body','cardio'
  )),
  secondary_muscle_groups jsonb not null default '[]'::jsonb,
  equipment text not null check (equipment in (
    'barbell','dumbbell','machine','cable','bodyweight','kettlebell','band','other'
  )),
  notes text,
  video_url text,
  created_at timestamptz not null default now()
);

-- Replaces the old global UNIQUE(name). Two users may each have their own "Bench Press",
-- a single user may not have two of their own, and a custom name may shadow a global one.
create unique index exercises_global_name_uniq
  on exercises (lower(name)) where user_id is null;
create unique index exercises_user_name_uniq
  on exercises (user_id, lower(name)) where user_id is not null;

-- ---------- Routines ----------

create table routines (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Redundant given the PK, but required as the target of the composite FKs below.
  unique (id, user_id)
);

create table routine_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  routine_id bigint not null,
  exercise_id bigint not null references exercises (id) on delete restrict,
  -- Renamed from "order", which is reserved in Postgres and would need quoting forever.
  sort_order integer not null,
  target_sets integer not null default 3,
  target_reps_min integer not null default 8,
  target_reps_max integer not null default 12,
  target_rpe double precision,
  rest_seconds integer not null default 90,
  group_id text,
  group_type text check (group_type in ('superset','circuit','dropset')),
  foreign key (routine_id, user_id)
    references routines (id, user_id) on delete cascade
);

-- ---------- Workouts ----------

create table workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  date timestamptz not null default now(),
  routine_id bigint,
  notes text,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_seconds integer,
  unique (id, user_id),
  foreign key (routine_id, user_id)
    references routines (id, user_id) on delete set null
);

-- The app assumes at most one workout in progress. Previously that was a global assumption
-- in a query; here it is enforced per user by the database.
create unique index workouts_one_active_per_user
  on workouts (user_id) where finished_at is null;

create table workout_sets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  workout_id bigint not null,
  exercise_id bigint not null references exercises (id) on delete restrict,
  set_number integer not null,
  weight double precision not null,
  reps integer not null,
  rpe double precision,
  is_warmup boolean not null default false,
  -- Denormalised at insert time by the same PR logic the app has always used.
  is_pr boolean not null default false,
  group_id text,
  completed_at timestamptz not null default now(),
  foreign key (workout_id, user_id)
    references workouts (id, user_id) on delete cascade
);

-- ---------- Body stats ----------

create table body_stats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  -- A real calendar day. Previously a UTC-midnight timestamp rendered with local-time
  -- formatting, which displayed the wrong day for negative UTC offsets.
  date date not null,
  weight_kg double precision,
  measurements jsonb,
  photo_url text,
  notes text
);

-- ---------- Weekly split ----------

create table weekly_split_days (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  day_of_week integer not null check (day_of_week between 0 and 6),
  label text,
  routine_id bigint,
  -- Makes PUT /split/:dayOfWeek a genuine upsert instead of select-then-branch.
  unique (user_id, day_of_week),
  foreign key (routine_id, user_id)
    references routines (id, user_id) on delete set null
);

-- ---------- Settings ----------
-- Was a singleton row with id = 1. The user is now the key.

create table user_settings (
  user_id uuid primary key references auth.users (id) on delete cascade,
  weight_unit text not null default 'lbs' check (weight_unit in ('kg','lbs')),
  default_rest_seconds integer not null default 90,
  timezone text not null default 'UTC'
);

-- ---------- Triggers ----------

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger routines_set_updated_at
  before update on routines
  for each row execute function set_updated_at();

-- Give every new account its settings row. Done in the database so accounts created by
-- OAuth, an invite, or the dashboard get one too, not only those from the signup form.
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_settings (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
